name: gtd_plus
description: "A modern GTD app with SQLite and alarm notifications."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 # MODIFICADO: Adicionado o novo pacote
  awesome_notifications: ^0.10.1

  # Local SQLite database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Simple state management
  provider: ^6.1.2
  
  # Date formatting
  intl: ^0.20.2 
  
  # For stable unique IDs
  uuid: ^4.4.0

  # para editar
  flutter_quill: ^11.4.2 # Adicione esta linha para o editor de texto
  image_picker: ^1.2.0

  quill_native_bridge: ^11.0.1
  # --- NOVA FERRAMENTA PARA DESENHAR IMAGENS ---
  flutter_quill_extensions: ^11.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true

  # Make sure to create this folder and add your alarm sound file
  assets:
    - assets/sounds/alarm.mp3
    - assets/images/logo.png
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
    - family: Serif
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
    - family: Verdana
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf # Usando Inter como fallback para Verdana
        - asset: assets/fonts/SourceSans3-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  # min_sdk_android: 21 # opcional